name: Deploy to Server

on:
  push:
    branches:
      - main # ou o branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Servers
      run: |
        ssh -o StrictHostKeyChecking=no root@104.251.212.234 'cd /var/www/html/api.gummy.com.br && git pull'
